image: freebsd/latest

packages:
  - tex-dvipsk
  - tex-formats
  - texlive-base
  - texlive-texmf
  - tex-xetex
  - zip
sources:
  - https://git.sr.ht/~samwhited/poetrytex
tasks:
- build: |
   cd poetrytex/
   make
   make poetrytex.zip
